load("@rules_proto//proto:defs.bzl", "proto_library")

package(
    default_visibility = ["//visibility:public"],
)

proto_library(
    name = "helloworld_proto",
    srcs = ["helloworld.proto"],
)

proto_library(
    name = "routeguide_proto",
    srcs = ["routeguide.proto"],
)
